name: flutter_sample_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.13
  flutter_slidable: ^1.2.0
  import_sorter: ^4.6.0
  freezed_annotation:
  json_serializable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  provider: ^6.0.2
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  flutter_gen_runner: ^4.1.6
  build_runner:
  freezed:

flutter_gen:
  output: lib/gen/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/todo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/todo_splash.png"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schyler-Regular.ttf
        - asset: fonts/Schyler-Italic.ttf
          style: italic
    - family: Trajan Pro
      fonts:
        - asset: fonts/TrajanPro.ttf
        - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
