name: flutter_riverpod_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Logger
  simple_logger:

  # LocalDatabase
  shared_preferences:

  # Riverpod
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  json_annotation:

  # Firebase
  firebase_core: ^1.16.0
  cloud_firestore:
  firebase_auth:
  firebase_storage:

  # Image
  image_picker:
  image_gallery_saver:
  image_cropper:
  flutter_image_compress:
  extended_image: ^7.0.0-dev.1

  # Picker
  numberpicker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0

  # Serializer
  json_serializable:

  # Code generator
  build_runner: ^2.1.10
  freezed: ^2.0.3+1
  flutter_gen_runner:

  # Other
  flutter_launcher_icons:

flutter_gen:
  output: lib/gen/
  line_length: 80


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
