name: flutter_json_api
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  logger: ^1.1.0

  flutter:
    sdk: flutter

  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  gap: ^2.0.0
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any
  json_serializable: ^6.3.1
  flutter_gen_runner: ^4.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/gen/
